apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.names.fullname" . }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
data:
  du-template.yml: |
{{ tpl (.Files.Get "resources/du-template.yml") . | indent 4 }}